In [2]:
import pandas as pd
import os

In [4]:

CSV_DIR = "datasets/csv_datasets/raw_datasets"

PATIENT_DOCTOR_FILE = os.path.join(
    CSV_DIR,
    "Healthcare Patient-Doctor Conversation Dataset (50K Samples).csv",
)

MEDQUAD_FILE = os.path.join(
    CSV_DIR,
    "medquad.csv",
)

MTSAMPLES_FILE = os.path.join(
    CSV_DIR,
    "mtsamples.csv",
)

OUTPUT_PATH = "datasets/csv_datasets/preprocessed_datasets"

In [ ]:
data1 = pd.read_csv(PATIENT_DOCTOR_FILE)
data2 = pd.read_csv(MEDQUAD_FILE)
data3 = pd.read_csv(MTSAMPLES_FILE)

In [6]:
data1.head(2)

,patient_input,doctor_response,age,gender,condition,symptom,duration,severity,intent,category
0,I am a 68-year-old Other experiencing severe c...,Your symptoms sound serious. It is strongly ad...,68,Other,Obesity,severe chest pain,for a few hours,severe,urgency,cardio
1,I have been having joint pain for a few hours....,Consider seeking medical advice if symptoms do...,7,Female,Diabetes,joint pain,for a few hours,moderate,advice,musculoskeletal

In [7]:
data2.head(2)

,question,answer,source,focus_area
0,What is (are) Glaucoma ?,Glaucoma is a group of diseases that can damag...,NIHSeniorHealth,Glaucoma
1,What causes Glaucoma ?,"Nearly 2.7 million people have glaucoma, a lea...",NIHSeniorHealth,Glaucoma

In [8]:
data3.head(3)

,Unnamed: 0,description,medical_specialty,sample_name,transcription,keywords
0,0,A 23-year-old white female presents with comp...,Allergy / Immunology,Allergic Rhinitis,"SUBJECTIVE:, This 23-year-old white female pr...","allergy / immunology, allergic rhinitis, aller..."
1,1,Consult for laparoscopic gastric bypass.,Bariatrics,Laparoscopic Gastric Bypass Consult - 2,"PAST MEDICAL HISTORY:, He has difficulty climb...","bariatrics, laparoscopic gastric bypass, weigh..."
2,2,Consult for laparoscopic gastric bypass.,Bariatrics,Laparoscopic Gastric Bypass Consult - 1,"HISTORY OF PRESENT ILLNESS: , I have seen ABC ...","bariatrics, laparoscopic gastric bypass, heart..."

### Data 1

In [9]:
data1.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   patient_input    50000 non-null  str
 1   doctor_response  50000 non-null  str
 2   age              50000 non-null  int64
 3   gender           50000 non-null  str
 4   condition        42884 non-null  str
 5   symptom          50000 non-null  str
 6   duration         50000 non-null  str
 7   severity         50000 non-null  str
 8   intent           50000 non-null  str
 9   category         50000 non-null  str
dtypes: int64(1), str(9)
memory usage: 3.8 MB

In [10]:
print(data1["condition"])

0                 Obesity
1                Diabetes
2        Thyroid Disorder
3        Thyroid Disorder
4                     NaN
               ...
49995        Hypertension
49996    Thyroid Disorder
49997       Heart Disease
49998             Obesity
49999            Diabetes
Name: condition, Length: 50000, dtype: str

In [11]:
data1["condition"] = data1["condition"].fillna(data1["condition"].mode()[0])

In [12]:
data1.isnull().sum()

patient_input      0
doctor_response    0
age                0
gender             0
condition          0
symptom            0
duration           0
severity           0
intent             0
category           0
dtype: int64

In [13]:
data1.duplicated().sum()

np.int64(1137)

In [15]:
data1 = data1.drop_duplicates()

In [17]:
data1.shape

(48863, 10)

In [ ]:
data1.to_csv(f"{OUTPUT_PATH}/dataset1.csv", index=False)

### data 2

In [19]:
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 16412 entries, 0 to 16411
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   question    16412 non-null  str
 1   answer      16407 non-null  str
 2   source      16412 non-null  str
 3   focus_area  16398 non-null  str
dtypes: str(4)
memory usage: 513.0 KB

In [20]:
data2 = data2.dropna()

In [21]:
data2.isnull().sum()

question      0
answer        0
source        0
focus_area    0
dtype: int64

In [22]:
data2.duplicated().sum()

np.int64(48)

In [23]:
data2 = data2.drop_duplicates()

In [24]:
data2.shape

(16345, 4)

In [25]:
data2.to_csv(f"{OUTPUT_PATH}/dataset2.csv", index=False)

### data 3

In [7]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 4999 entries, 0 to 4998
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         4999 non-null   int64
 1   description        4999 non-null   str
 2   medical_specialty  4999 non-null   str
 3   sample_name        4999 non-null   str
 4   transcription      4966 non-null   str
 5   keywords           3931 non-null   str
dtypes: int64(1), str(5)
memory usage: 234.5 KB

In [8]:
data3 = data3.dropna()

In [9]:
data3.isnull().sum()

Unnamed: 0           0
description          0
medical_specialty    0
sample_name          0
transcription        0
keywords             0
dtype: int64

In [13]:
data3.duplicated().sum()

np.int64(0)

In [16]:
data3.shape

(3898, 5)

In [15]:
data3 = data3.iloc[:,1:]

In [17]:
data3.info()

<class 'pandas.DataFrame'>
Index: 3898 entries, 0 to 4995
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   description        3898 non-null   str
 1   medical_specialty  3898 non-null   str
 2   sample_name        3898 non-null   str
 3   transcription      3898 non-null   str
 4   keywords           3898 non-null   str
dtypes: str(5)
memory usage: 182.7 KB

In [18]:
data3.to_csv(f"{OUTPUT_PATH}/dataset3.csv", index=False)